//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinHongKongArduino.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinHongKongArduino.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ROM に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CertType_00 {
            get {
                return ResourceManager.GetString("CertType_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ROM+RAM に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CertType_01 {
            get {
                return ResourceManager.GetString("CertType_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ROM+RAM+BB に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CertType_02 {
            get {
                return ResourceManager.GetString("CertType_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ROM+拡張 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CertType_03 {
            get {
                return ResourceManager.GetString("CertType_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ROM+RAM+拡張 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CertType_04 {
            get {
                return ResourceManager.GetString("CertType_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ROM+RAM+BB+拡張 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CertType_05 {
            get {
                return ResourceManager.GetString("CertType_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ROM+BB+拡張 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CertType_06 {
            get {
                return ResourceManager.GetString("CertType_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ROM+RAM+BB+拡張+RTC に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CertType_09 {
            get {
                return ResourceManager.GetString("CertType_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ROM+RAM+BB+拡張+OC に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CertType_0A {
            get {
                return ResourceManager.GetString("CertType_0A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DSP に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CoPro_00 {
            get {
                return ResourceManager.GetString("CoPro_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GSU に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CoPro_10 {
            get {
                return ResourceManager.GetString("CoPro_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OBC1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CoPro_20 {
            get {
                return ResourceManager.GetString("CoPro_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SA-1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CoPro_30 {
            get {
                return ResourceManager.GetString("CoPro_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   S-DD1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CoPro_40 {
            get {
                return ResourceManager.GetString("CoPro_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   S-RTC に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CoPro_50 {
            get {
                return ResourceManager.GetString("CoPro_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Japan に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Country_00 {
            get {
                return ResourceManager.GetString("Country_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nouth America に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Country_01 {
            get {
                return ResourceManager.GetString("Country_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All of Europe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Country_02 {
            get {
                return ResourceManager.GetString("Country_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scandinavia に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Country_03 {
            get {
                return ResourceManager.GetString("Country_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Europe (French only) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Country_06 {
            get {
                return ResourceManager.GetString("Country_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dutch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Country_07 {
            get {
                return ResourceManager.GetString("Country_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spanish に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Country_08 {
            get {
                return ResourceManager.GetString("Country_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   German に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Country_09 {
            get {
                return ResourceManager.GetString("Country_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Italian に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Country_0A {
            get {
                return ResourceManager.GetString("Country_0A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chinese に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Country_0B {
            get {
                return ResourceManager.GetString("Country_0B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Korean に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Country_0D {
            get {
                return ResourceManager.GetString("Country_0D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Common に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Country_0E {
            get {
                return ResourceManager.GetString("Country_0E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Canada に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Country_0F {
            get {
                return ResourceManager.GetString("Country_0F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Brazil に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Country_10 {
            get {
                return ResourceManager.GetString("Country_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Australia に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Country_11 {
            get {
                return ResourceManager.GetString("Country_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other Variation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Country_12 {
            get {
                return ResourceManager.GetString("Country_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other Variation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Country_13 {
            get {
                return ResourceManager.GetString("Country_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other Variation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Country_14 {
            get {
                return ResourceManager.GetString("Country_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExRAMSize_00 {
            get {
                return ResourceManager.GetString("ExRAMSize_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   16 KBit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExRAMSize_01 {
            get {
                return ResourceManager.GetString("ExRAMSize_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   64 KBit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExRAMSize_02 {
            get {
                return ResourceManager.GetString("ExRAMSize_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   256 KBit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExRAMSize_03 {
            get {
                return ResourceManager.GetString("ExRAMSize_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   512 KBit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExRAMSize_05 {
            get {
                return ResourceManager.GetString("ExRAMSize_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 MBit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExRAMSize_0A {
            get {
                return ResourceManager.GetString("ExRAMSize_0A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;Invalid License Code&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_00 {
            get {
                return ResourceManager.GetString("License_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nintendo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_01 {
            get {
                return ResourceManager.GetString("License_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zamuse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_05 {
            get {
                return ResourceManager.GetString("License_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Capcom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_08 {
            get {
                return ResourceManager.GetString("License_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HOT B に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_09 {
            get {
                return ResourceManager.GetString("License_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jaleco に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_0A {
            get {
                return ResourceManager.GetString("License_0A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STORM (Sales Curve) (1) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_0B {
            get {
                return ResourceManager.GetString("License_0B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mebio Software に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_0F {
            get {
                return ResourceManager.GetString("License_0F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gremlin Graphics に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_12 {
            get {
                return ResourceManager.GetString("License_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   COBRA Team に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_15 {
            get {
                return ResourceManager.GetString("License_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Human/Field に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_16 {
            get {
                return ResourceManager.GetString("License_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hudson Soft に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_18 {
            get {
                return ResourceManager.GetString("License_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yanoman に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_1A {
            get {
                return ResourceManager.GetString("License_1A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tecmo (1) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_1C {
            get {
                return ResourceManager.GetString("License_1C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Forum に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_1E {
            get {
                return ResourceManager.GetString("License_1E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Park Place Productions / VIRGIN に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_1F {
            get {
                return ResourceManager.GetString("License_1F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tokai Engeneering (SUNSOFT?) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_21 {
            get {
                return ResourceManager.GetString("License_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   POW に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_22 {
            get {
                return ResourceManager.GetString("License_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loriciel / Micro World に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_23 {
            get {
                return ResourceManager.GetString("License_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enix に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_26 {
            get {
                return ResourceManager.GetString("License_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kemco (1) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_28 {
            get {
                return ResourceManager.GetString("License_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seta Co.,Ltd. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_29 {
            get {
                return ResourceManager.GetString("License_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visit Co.,Ltd. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_2D {
            get {
                return ResourceManager.GetString("License_2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HECT に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_35 {
            get {
                return ResourceManager.GetString("License_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loriciel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_3D {
            get {
                return ResourceManager.GetString("License_3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seika Corp. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_40 {
            get {
                return ResourceManager.GetString("License_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UBI Soft に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_41 {
            get {
                return ResourceManager.GetString("License_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spectrum Holobyte に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_47 {
            get {
                return ResourceManager.GetString("License_47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Irem に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_49 {
            get {
                return ResourceManager.GetString("License_49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Raya Systems/Sculptured Software に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_4B {
            get {
                return ResourceManager.GetString("License_4B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Renovation Pruducts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_4C {
            get {
                return ResourceManager.GetString("License_4C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Malibu Games (T*HQ Inc.) / Black Pearl に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_4D {
            get {
                return ResourceManager.GetString("License_4D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   U.S. Gold に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_4F {
            get {
                return ResourceManager.GetString("License_4F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Absolute Entertainment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_50 {
            get {
                return ResourceManager.GetString("License_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Acclaim に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_51 {
            get {
                return ResourceManager.GetString("License_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Activision に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_52 {
            get {
                return ResourceManager.GetString("License_52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   American Sammy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_53 {
            get {
                return ResourceManager.GetString("License_53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GameTek に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_54 {
            get {
                return ResourceManager.GetString("License_54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hi Tech に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_55 {
            get {
                return ResourceManager.GetString("License_55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LJN Toys に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_56 {
            get {
                return ResourceManager.GetString("License_56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mindscape に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_5A {
            get {
                return ResourceManager.GetString("License_5A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Technos Japan Corp. (Tradewest) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_5D {
            get {
                return ResourceManager.GetString("License_5D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   American Softworks Corp. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_5F {
            get {
                return ResourceManager.GetString("License_5F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Titus に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_60 {
            get {
                return ResourceManager.GetString("License_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Virgin Games に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_61 {
            get {
                return ResourceManager.GetString("License_61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maxis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_62 {
            get {
                return ResourceManager.GetString("License_62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ocean に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_67 {
            get {
                return ResourceManager.GetString("License_67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Electronic Arts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_69 {
            get {
                return ResourceManager.GetString("License_69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Laser Beam に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_6B {
            get {
                return ResourceManager.GetString("License_6B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Elite に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_6E {
            get {
                return ResourceManager.GetString("License_6E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Electro Brain に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_6F {
            get {
                return ResourceManager.GetString("License_6F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Infogrames に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_70 {
            get {
                return ResourceManager.GetString("License_70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interplay に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_71 {
            get {
                return ResourceManager.GetString("License_71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LucasArts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_72 {
            get {
                return ResourceManager.GetString("License_72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sculptured Soft に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_73 {
            get {
                return ResourceManager.GetString("License_73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STORM (Sales Curve) (2) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_75 {
            get {
                return ResourceManager.GetString("License_75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   THQ Software に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_78 {
            get {
                return ResourceManager.GetString("License_78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Accolade Inc. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_79 {
            get {
                return ResourceManager.GetString("License_79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Triffix Entertainment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_7A {
            get {
                return ResourceManager.GetString("License_7A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Microprose に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_7C {
            get {
                return ResourceManager.GetString("License_7C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kemco (2) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_7F {
            get {
                return ResourceManager.GetString("License_7F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Namcot/Namco Ltd. (1) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_82 {
            get {
                return ResourceManager.GetString("License_82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Koei/Koei! (second license?) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_84 {
            get {
                return ResourceManager.GetString("License_84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tokuma Shoten Intermedia に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_86 {
            get {
                return ResourceManager.GetString("License_86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DATAM-Polystar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_88 {
            get {
                return ResourceManager.GetString("License_88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bullet-Proof Software に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_8B {
            get {
                return ResourceManager.GetString("License_8B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vic Tokai に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_8C {
            get {
                return ResourceManager.GetString("License_8C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I&apos;Max に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_8F {
            get {
                return ResourceManager.GetString("License_8F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CHUN Soft に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_91 {
            get {
                return ResourceManager.GetString("License_91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Video System Co., Ltd. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_92 {
            get {
                return ResourceManager.GetString("License_92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BEC に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_93 {
            get {
                return ResourceManager.GetString("License_93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kaneco に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_97 {
            get {
                return ResourceManager.GetString("License_97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pack in Video に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_99 {
            get {
                return ResourceManager.GetString("License_99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nichibutsu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_9A {
            get {
                return ResourceManager.GetString("License_9A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TECMO (2) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_9B {
            get {
                return ResourceManager.GetString("License_9B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Imagineer Co. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_9C {
            get {
                return ResourceManager.GetString("License_9C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wolf Team に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_A0 {
            get {
                return ResourceManager.GetString("License_A0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Konami に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_A4 {
            get {
                return ResourceManager.GetString("License_A4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   K.Amusement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_A5 {
            get {
                return ResourceManager.GetString("License_A5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Takara に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_A7 {
            get {
                return ResourceManager.GetString("License_A7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Technos Jap. ???? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_A9 {
            get {
                return ResourceManager.GetString("License_A9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JVC に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_AA {
            get {
                return ResourceManager.GetString("License_AA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toei Animation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_AC {
            get {
                return ResourceManager.GetString("License_AC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toho に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_AD {
            get {
                return ResourceManager.GetString("License_AD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Namcot/Namco Ltd. (2) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_AF {
            get {
                return ResourceManager.GetString("License_AF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ASCII Co. Activison に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_B1 {
            get {
                return ResourceManager.GetString("License_B1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BanDai America に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_B2 {
            get {
                return ResourceManager.GetString("License_B2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enix に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_B4 {
            get {
                return ResourceManager.GetString("License_B4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Halken に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_B6 {
            get {
                return ResourceManager.GetString("License_B6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Culture Brain に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_BA {
            get {
                return ResourceManager.GetString("License_BA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sunsoft に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_BB {
            get {
                return ResourceManager.GetString("License_BB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toshiba EMI/System Vision に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_BC {
            get {
                return ResourceManager.GetString("License_BC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sony (Japan) / Imagesoft に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_BD {
            get {
                return ResourceManager.GetString("License_BD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sammy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_BF {
            get {
                return ResourceManager.GetString("License_BF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Taito に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_C0 {
            get {
                return ResourceManager.GetString("License_C0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kemco (3) ???? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_C2 {
            get {
                return ResourceManager.GetString("License_C2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Square に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_C3 {
            get {
                return ResourceManager.GetString("License_C3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NHK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_C4 {
            get {
                return ResourceManager.GetString("License_C4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data East に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_C5 {
            get {
                return ResourceManager.GetString("License_C5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tonkin House に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_C6 {
            get {
                return ResourceManager.GetString("License_C6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KOEI に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_C8 {
            get {
                return ResourceManager.GetString("License_C8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Konami USA に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_CA {
            get {
                return ResourceManager.GetString("License_CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Meldac/KAZe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_CD {
            get {
                return ResourceManager.GetString("License_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PONY CANYON に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_CE {
            get {
                return ResourceManager.GetString("License_CE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sotsu Agency に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_CF {
            get {
                return ResourceManager.GetString("License_CF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sofel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_D1 {
            get {
                return ResourceManager.GetString("License_D1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quest Corp. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_D2 {
            get {
                return ResourceManager.GetString("License_D2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sigma に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_D3 {
            get {
                return ResourceManager.GetString("License_D3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Naxat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_D6 {
            get {
                return ResourceManager.GetString("License_D6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Capcom Co., Ltd. (2) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_D8 {
            get {
                return ResourceManager.GetString("License_D8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Banpresto に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_D9 {
            get {
                return ResourceManager.GetString("License_D9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiro に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_DB {
            get {
                return ResourceManager.GetString("License_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NCS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_DD {
            get {
                return ResourceManager.GetString("License_DD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Human Entertainment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_DE {
            get {
                return ResourceManager.GetString("License_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ringler Studios に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_DF {
            get {
                return ResourceManager.GetString("License_DF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   K.K. DCE / Jaleco に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_E0 {
            get {
                return ResourceManager.GetString("License_E0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sotsu Agency に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_E2 {
            get {
                return ResourceManager.GetString("License_E2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T&amp;ESoft に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_E4 {
            get {
                return ResourceManager.GetString("License_E4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EPOCH Co.,Ltd. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_E5 {
            get {
                return ResourceManager.GetString("License_E5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Athena に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_E7 {
            get {
                return ResourceManager.GetString("License_E7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Asmik に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_E8 {
            get {
                return ResourceManager.GetString("License_E8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Natsume に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_E9 {
            get {
                return ResourceManager.GetString("License_E9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   King/A Wave に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_EA {
            get {
                return ResourceManager.GetString("License_EA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Atlus に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_EB {
            get {
                return ResourceManager.GetString("License_EB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sony Music に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_EC {
            get {
                return ResourceManager.GetString("License_EC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Psygnosis / igs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_EE {
            get {
                return ResourceManager.GetString("License_EE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Beam Software に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_F3 {
            get {
                return ResourceManager.GetString("License_F3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tec Magik に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_F4 {
            get {
                return ResourceManager.GetString("License_F4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hudson Soft に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_FF {
            get {
                return ResourceManager.GetString("License_FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LoROM に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MAP_00 {
            get {
                return ResourceManager.GetString("MAP_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HiROM に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MAP_01 {
            get {
                return ResourceManager.GetString("MAP_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LoROM+S-DD1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MAP_02 {
            get {
                return ResourceManager.GetString("MAP_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LoROM+SA-1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MAP_03 {
            get {
                return ResourceManager.GetString("MAP_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExHiROM に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MAP_05 {
            get {
                return ResourceManager.GetString("MAP_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExHiROM+SPC7110 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MAP_0A {
            get {
                return ResourceManager.GetString("MAP_0A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   なし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RAMSize_00 {
            get {
                return ResourceManager.GetString("RAMSize_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   16Kbit(2KB) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RAMSize_01 {
            get {
                return ResourceManager.GetString("RAMSize_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   32Kbit(4KB) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RAMSize_02 {
            get {
                return ResourceManager.GetString("RAMSize_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   64Kbit(8KB) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RAMSize_03 {
            get {
                return ResourceManager.GetString("RAMSize_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   128Kbit(16KB) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RAMSize_04 {
            get {
                return ResourceManager.GetString("RAMSize_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   256Kbit(32KB) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RAMSize_05 {
            get {
                return ResourceManager.GetString("RAMSize_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   512Kbit(64KB) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RAMSize_06 {
            get {
                return ResourceManager.GetString("RAMSize_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1Mbit(128KB) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RAMSize_07 {
            get {
                return ResourceManager.GetString("RAMSize_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0.25Mbit(32KB) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ROMSize_01 {
            get {
                return ResourceManager.GetString("ROMSize_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0.50Mbit(64KB) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ROMSize_02 {
            get {
                return ResourceManager.GetString("ROMSize_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0.75Mbit(96KB) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ROMSize_03 {
            get {
                return ResourceManager.GetString("ROMSize_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1.00Mbit(128KB) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ROMSize_04 {
            get {
                return ResourceManager.GetString("ROMSize_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1.25Mbit(160KB) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ROMSize_05 {
            get {
                return ResourceManager.GetString("ROMSize_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1.50Mbit(192KB) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ROMSize_06 {
            get {
                return ResourceManager.GetString("ROMSize_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1.75Mbit(224KB) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ROMSize_07 {
            get {
                return ResourceManager.GetString("ROMSize_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2Mbit(256KB) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ROMSize_08 {
            get {
                return ResourceManager.GetString("ROMSize_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   4Mbit(512KB) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ROMSize_09 {
            get {
                return ResourceManager.GetString("ROMSize_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   8Mbit(1MB) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ROMSize_0A {
            get {
                return ResourceManager.GetString("ROMSize_0A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   16Mbit(2MB) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ROMSize_0B {
            get {
                return ResourceManager.GetString("ROMSize_0B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   32Mbit(4MB) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ROMSize_0C {
            get {
                return ResourceManager.GetString("ROMSize_0C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   64Mbit(8MB) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ROMSize_0D {
            get {
                return ResourceManager.GetString("ROMSize_0D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Slow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ROMSpeed_20 {
            get {
                return ResourceManager.GetString("ROMSpeed_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fast に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ROMSpeed_30 {
            get {
                return ResourceManager.GetString("ROMSpeed_30", resourceCulture);
            }
        }
    }
}
